services:
  - type: web
    name: laravel-map
    env: docker
    plan: free
    autoDeploy: true
    region: frankfurt  # أو غيّرها للمنطقة اللي اخترتها
    envVars:
      - key: APP_KEY
        value: base64:D7Pl6ikdENFcPSC+VVFldGtjEfcCtTXGLtard2L+7sc=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d4aa65ndiees73cvn01g-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: laravel_map
      - key: DB_USERNAME
        value: laravel_map_user
      - key: DB_PASSWORD
        value: ZdmawjXSRC9TTsgWAlk7EaJonbLH6op0
